ci:
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version. If bumping this, please also bump requirements-dev.in
  rev: v0.5.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  # mypy - static type checker. If bumping this, bump requirements-dev.txt as well
  rev: 'v1.11.0'  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      # verbose: true
      # args: [--show-error-codes]
      exclude: ^(submit|find)/.*$
      additional_dependencies: [
        pandas-stubs,
        sqlalchemy-stubs,
        types-beautifulsoup4,
        types-colorama,
        types-flask,
        types-Flask-Migrate,
        types-jmespath,
        types-openpyxl,
        types-psycopg2,
        types-python-dateutil,
        types-Pygments,
        types-PyMySQL,
        types-PyYAML,
        types-requests,
        types-setuptools,
        types-flask-sqlalchemy,
        ]
