ci:
  autofix_prs: false

  # mypy needs a lot of dependencies installed, and we hit limits in precommit.ci on the size of the dependencies
  # which causes precommit to fail. So we now run precommit mypy in github actions separately.
  skip: [mypy]

default_language_version:
    python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version. If bumping this, please also bump requirements-dev.in
  rev: v0.11.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: mypy
      name: Run type checks
      language: system
      types: [python]
      entry: mypy .
      pass_filenames: false
- repo: https://github.com/djlint/djLint
  rev: v1.36.4
  hooks:
    - id: djlint-jinja
      types_or: ['html', 'jinja']
