{
    "Crawley": "Crawley Borough Council",
    "Workington": "Cumberland Council",
    "Darlington": "Darlington Borough Council",
    "Derby City Centre, St Peters Cross": "Derby City Council",
    "Stainforth": "Doncaster Council",
    "Dover Town Centre and Waterfront": "Dover District Council",
    "Brierley Hill High Town Centre": "Dudley Metropolitan Borough Council",
    "Bishop Auckland": "Durham County Council",
    "Skegness": "East Lindsey District Council",
    "Goole": "East Riding of Yorkshire Council",
    "Burton": "East Staffordshire Borough Council",
    "Lowestoft": "East Suffolk Council",
    "Long Eaton": "Erewash Borough Council",
    "March High Street": "Fenland District Council",
    "Kirkham Town Centre": "Fylde Council",
    "Great Yarmouth": "Great Yarmouth Borough Council",
    "Runcorn": "Halton Borough Council",
    "Tottenham High Road": "Haringey Council",
    "Harlow": "Harlow District Council",
    "Wealdstone": "Harrow Council",
    "Hartlepool": "Hartlepool Borough Council",
    "Hastings": "Hastings Borough Council",
    "Hereford": "Herefordshire Council",
    "Buxton": "High Peak Borough Council",
    "St Neots": "Huntingdonshire District Council",
    "Ipswich": "Ipswich",
    "Dewsbury": "Ipswich Borough Council",
    "King's Lynn": "King's Lynn and West Norfolk",
    "Morley": "Kirklees Council",
    "Newhaven": "Lewes District Council",
    "Sutton High Street": "London Borough of Sutton Council",
    "Mansfield": "Mansfield District Council",
    "Chatham Town Centre": "Medway Council",
    "Middlesbrough Centre": "Middlesbrough Council",
    "Milton Keynes": "Milton Keynes City Council",
    "Newark-on-Trent": "Newark and Sherwood District Council ",
    "Newcastle-Under-Lyme Town Centre": "Newcastle-under-Lyme Borough Council",
    "Barnstaple": "North Devon Council",
    "Clay Cross": "North East Derbyshire District Council",
    "Grimsby Town Centre": "North East Lincolnshire Council",
    "Scunthorpe": "North Lincolnshire Council",
    "Corby": "North Northamptonshire Council",
    "Northallerton": "North Yorkshire Council",
    "Blyth Town Centre": "Northumberland County Council",
    "Norwich": "Norwich City Council",
    "Nottingham City Centre, West End Point": "Nottingham City Council",
    "Nuneaton Town Centre": "Nuneaton & Bedworth Borough Council",
    "Nuneaton": "Nuneaton and Bedworth",
    "Oldham": "Oldham Metropolitan Borough Council",
    "Nelson": "Pendle Borough Council",
    "Peterborough": "Peterborough City Council",
    "Plymouth City Centre": "Plymouth City Council",
    "Fratton": "Portsmouth City Council",
    "Preston": "Preston City Council",
    "Redcar": "Redcar & Cleveland Borough Council",
    "Redditch": "Redditch Borough Council ",
    "Rochdale Town Centre": "Rochdale Borough Council",
    "Rotherham": "Rotherham Metropolitan Borough Council",
    "Woolwich Town Centre": "Royal Borough of Greenwich",
    "West Bromwich": "Sandwell Council",
    "Southport": "Sefton Metropolitan Borough Council",
    "Sheffield High Street": "Sheffield City Council",
    "Yeovil": "Somerset Council",
    "Kingswood": "South Gloucestershire Council",
    "Grantham": "South Kesteven District Council",
    "Leyland": "South Ribble Borough Council",
    "South Shields": "South Tyneside Council",
    "Old Kent Road": "Southwark Council",
    "St Helens": "St Helens Borough Council",
    "Stafford": "Stafford Borough Council",
    "Stevenage": "Stevenage Borough Council",
    "Stockport": "Stockport Metropolitan Borough Council",
    "Stockton": "Stockton-On-Tees Borough Council",
    "Sunderland City Centre": "Sunderland City Council",
    "Swindon": "Swindon Borough Council",
    "Tamworth Town Centre": "Tamworth Borough Council",
    "Newton Abbot": "Teignbridge District Council",
    "Telford": "Telford & Wrekin Council ",
    "Ramsgate": "Thanet District Council",
    "Tilbury": "Thurrock Borough Council",
    "Paignton": "Torbay Council",
    "Stretford": "Trafford Council",
    "Wakefield": "Wakefield Metropolitan Borough Council",
    "Walsall": "Walsall Council",
    "Putney Town Centre": "Wandsworth Council",
    "Warrington": "Warrington Borough Council",
    "Leamington Town Centre": "Warwick District Council",
    "Northampton": "West Northamptonshire Council",
    "Barrow": "Westmorland & Furness Council ",
    "Wigan": "Wigan Council",
    "Trowbridge": "Wiltshire Council",
    "New Ferry": "Wirral Council",
    "Blackfriars - Northern City Centre": "Worcester City Council",
    "Kidderminster": "Wyre Forest District Council",
}
