[_]
schema-version = "0.2"
id = "sample.nodejs+python.app"
name = "Sample Nodejs & Python App"
version = "1.0.0"

[[io.buildpacks.group]]
uri = "heroku/python"

[[io.buildpacks.group]]
uri = "heroku/nodejs"

[[io.buildpacks.group]]
uri = "heroku/nodejs-npm-install"

[[io.buildpacks.group]]
uri = "heroku/procfile"
