[ _ ]
schema-version = "0.2"

[[ io.buildpacks.build.env ]]
  name = "BP_CPYTHON_VERSION"
  value = "3.11.*" # any valid semver constraints (e.g. 3.6.7, 3.*) are acceptable

[[ io.buildpacks.build.env ]]
  name = "BP_NODE_PROJECT_PATH"
  value = "vite"

[[ io.buildpacks.build.env ]]
  name = "BP_NODE_RUN_SCRIPTS"
  value = "build"
