"""empty message

Revision ID: 004_alter_field_nullabilities_for_round_1_data
Revises: dee94a0080e2
Create Date: 2023-06-16 10:12:27.000185

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "004_alter_field_nullabilities_for_round_1_data"
down_revision = "dee94a0080e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.alter_column("location_multiplicity", existing_type=sa.VARCHAR(length=8), nullable=True)

    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column("start_date", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("end_date", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("adjustment_request_status", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column("adjustment_request_status", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("end_date", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("start_date", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.alter_column("location_multiplicity", existing_type=sa.VARCHAR(length=8), nullable=False)

    # ### end Alembic commands ###
