"""
This migration relaxes the Project Progress table to allow null values into the following columns:
- delivery_status
- delivery_rag
- spend_rag
- risk_rag

Revision ID: 005_relax_proj_prog_nulls
Revises: 004_alter_field_nullabilities
Create Date: 2023-06-29 12:15:56.084291

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "005_relax_proj_prog_nulls"
down_revision = "004_alter_field_nullabilities"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column(
            "delivery_status",
            existing_type=postgresql.ENUM(
                "NOT_YET_STARTED",
                "ONGOING_ON_TRACK",
                "ONGOING_DELAYED",
                "COMPLETED",
                "OTHER",
                name="project_progress_delivery_status",
            ),
            nullable=True,
        )
        batch_op.alter_column(
            "delivery_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_delivery_rag"),
            nullable=True,
        )
        batch_op.alter_column(
            "spend_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_spend_rag"),
            nullable=True,
        )
        batch_op.alter_column(
            "risk_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_risk_rag"),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column(
            "risk_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_risk_rag"),
            nullable=False,
        )
        batch_op.alter_column(
            "spend_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_spend_rag"),
            nullable=False,
        )
        batch_op.alter_column(
            "delivery_rag",
            existing_type=postgresql.ENUM("ONE", "TWO", "THREE", "FOUR", "FIVE", name="project_progress_delivery_rag"),
            nullable=False,
        )
        batch_op.alter_column(
            "delivery_status",
            existing_type=postgresql.ENUM(
                "NOT_YET_STARTED",
                "ONGOING_ON_TRACK",
                "ONGOING_DELAYED",
                "COMPLETED",
                "OTHER",
                name="project_progress_delivery_status",
            ),
            nullable=False,
        )

    # ### end Alembic commands ###
