"""empty message

Revision ID: 008_add_new_round_4_cols
Revises: 007_index_joins_and_filters
Create Date: 2023-09-26 10:34:56.463888

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "008_add_new_round_4_cols"
down_revision = "007_index_joins_and_filters"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.add_column(sa.Column("delivery_stage", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("leading_factor_of_delay", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.drop_column("leading_factor_of_delay")
        batch_op.drop_column("delivery_stage")

    # ### end Alembic commands ###
