"""empty message

Revision ID: 010_jsonb_migrate_test
Revises: 009_postcode_as_array
Create Date: 2024-01-24 11:27:35.340543

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.util.preloaded import orm

from core.db.entities import Funding

# revision identifiers, used by Alembic.
revision = "010_jsonb_migrate_test"
down_revision = "009_postcode_as_array"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.add_column(sa.Column("json_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Update existing rows with JSON data
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    funding_rows = session.query(Funding).all()
    for row in funding_rows:
        jsonb = {
            "start_date": str(row.start_date),
            "end_date": str(row.end_date),
            "funding_source_name": row.funding_source_name,
            "funding_source_type": row.funding_source_type,
            "secured": row.secured,
            "spend_for_reporting_period": row.spend_for_reporting_period,
            "status": row.status,
        }

        row.json_blob = jsonb

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.drop_column("json_blob")

    # ### end Alembic commands ###
