"""empty message

Revision ID: 011_remove_submission_file
Revises: 010_programme_junction
Create Date: 2024-02-19 10:29:11.913211

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "011_remove_submission_file"
down_revision = "010_programme_junction"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.drop_column("submission_file")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("submission_file", postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
