"""Add programme_junction_id to output_data and funding

Revision ID: 013_add_programme_junction_to_tables
Revises: 012_event_data_to_jsonb
Create Date: 2024-02-26 14:37:37.825821

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "013_add_programme_junction_to_tables"
down_revision = "012_event_data_to_jsonb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("output_data", sa.Column("programme_junction_id", sa.GUID(), nullable=False))
    op.add_column("funding", sa.Column("programme_junction_id", sa.GUID(), nullable=False))

    op.create_foreign_key(
        "fk_output_data_programme_junction", "output_data", "programme_junction", ["programme_junction_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_funding_programme_junction", "funding", "programme_junction", ["programme_junction_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_funding_programme_junction", "funding", type_="foreignkey")
    op.drop_constraint("fk_output_data_programme_junction", "output_data", type_="foreignkey")

    op.drop_column("funding", "programme_junction_id")
    op.drop_column("output_data", "programme_junction_id")
    # ### end Alembic commands ###
