"""empty message

Revision ID: 014_project_table_to_jsonb
Revises: 013_all_event_tables_prog_j_id
Create Date: 2024-02-27 15:49:44.420890

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "014_project_table_to_jsonb"
down_revision = "013_all_event_tables_prog_j_id"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_data_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    op.execute(
        """
            UPDATE project_dim
            SET event_data_blob = jsonb_build_object(
                'gis_provided', gis_provided,
                'primary_intervention_theme', primary_intervention_theme,
                'location_multiplicity', location_multiplicity,
                'locations', locations,
                'lat_long', lat_long
            )
        """
    )

    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.drop_column("gis_provided")
        batch_op.drop_column("primary_intervention_theme")
        batch_op.drop_column("location_multiplicity")
        batch_op.drop_column("locations")
        batch_op.drop_column("lat_long")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lat_long", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("locations", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("location_multiplicity", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("primary_intervention_theme", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("gis_provided", sa.VARCHAR(), autoincrement=False, nullable=True))

    op.execute(
        """
            UPDATE project_dim
            SET
                lat_long = (event_data_blob ->> 'lat_long')::VARCHAR,
                locations = (event_data_blob ->> 'locations')::VARCHAR,
                location_multiplicity = (event_data_blob ->> 'location_multiplicity')::VARCHAR,
                primary_intervention_theme = (event_data_blob ->> 'primary_intervention_theme')::VARCHAR,
                gis_provided = (event_data_blob ->> 'gis_provided')::VARCHAR
        """
    )

    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.alter_column("locations", nullable=False)
        batch_op.alter_column("primary_intervention_theme", nullable=False)

    with op.batch_alter_table("project_dim", schema=None) as batch_op:
        batch_op.drop_column("event_data_blob")

    # ### end Alembic commands ###
