"""empty message

Revision ID: 014_add_pfc_table
Revises: 013_all_event_tables_prog_j_id
Create Date: 2024-02-28 11:16:58.767143

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import core

# revision identifiers, used by Alembic.
revision = "014_add_pfc_table"
down_revision = "013_all_event_tables_prog_j_id"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_finance_change",
        sa.Column("project_id", core.db.types.GUID(), nullable=True),
        sa.Column("event_data_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", core.db.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_dim.id"],
            name=op.f("fk_project_finance_change_project_id_project_dim"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_finance_change")),
    )
    with op.batch_alter_table("project_finance_change", schema=None) as batch_op:
        batch_op.create_index("ix_project_finance_change_join_project", ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_finance_change", schema=None) as batch_op:
        batch_op.drop_index("ix_project_finance_change_join_project")

    op.drop_table("project_finance_change")
    # ### end Alembic commands ###
