"""Add geospatial_dim table and postcode_prefix and itl_region mapping data

Revision ID: 022_add_geospatial_dim_table
Revises: 021_outcome_end_date_nullable
Create Date: 2024-03-06 16:13:06.143726

"""

import uuid  # noqa

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import data_store

# revision identifiers, used by Alembic.
revision = "022_add_geospatial_dim_table"
down_revision = "021_outcome_end_date_nullable"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "geospatial_dim",
        sa.Column("id", data_store.db.types.GUID(), nullable=False),
        sa.Column("postcode_prefix", sa.String(length=4), nullable=False),
        sa.Column("itl1_region_code", sa.String(), nullable=False),
        sa.Column("data_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geospatial_dim")),
        sa.UniqueConstraint("postcode_prefix", name=op.f("uq_geospatial_dim_postcode_prefix")),
    )

    with op.batch_alter_table("geospatial_dim", schema=None) as batch_op:
        batch_op.create_index("ix_geospatial_dim_filter_region", ["itl1_region_code"], unique=False)

    # The instantiated table, data and bulk insert below have been commented out to remove the data insert
    # from this migration script. It is already present in deployed environments, and in the case of new
    # deployments can be seeded via flask CLI commands. Flask CLI commands will also be used to seed new
    # db containers in local development, and we should not use alembic migrations to insert data again.

    # These actions should not be commented back in to the migration.

    # geospatial_dim = table(
    #     "geospatial_dim",
    #     column("id", core.db.types.GUID()),
    #     column("postcode_prefix", sa.String),
    #     column("itl1_region_code", sa.String),
    #     column("data_blob", postgresql.JSONB),
    # )

    # geospatial_data = [
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "AB",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "AL",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "B",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BA",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BB",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BD",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BH",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BL",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BN",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BR",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BS",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "BT",
    #         "itl1_region_code": "TLN",
    #         "data_blob": {"itl1_region_name": "Northern Ireland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CA",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CB",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CF",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CH",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CM",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CO",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CR",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CT",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CV",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "CW",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DA",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DD",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DE",
    #         "itl1_region_code": "TLF",
    #         "data_blob": {"itl1_region_name": "East Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DG",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DH",
    #         "itl1_region_code": "TLC",
    #         "data_blob": {"itl1_region_name": "North East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DL",
    #         "itl1_region_code": "TLC",
    #         "data_blob": {"itl1_region_name": "North East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DN",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DT",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "DY",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "E",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "EC",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "EH",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "EN",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "EX",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "FK",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "FY",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "G",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "GL",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "GU",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "GY",
    #         "itl1_region_code": "TLZ",
    #         "data_blob": {"itl1_region_name": "Non-ITL1 Region"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HA",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HD",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HG",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HP",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HR",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HS",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HU",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "HX",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "IG",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "IM",
    #         "itl1_region_code": "TLZ",
    #         "data_blob": {"itl1_region_name": "Non-ITL1 Region"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "IP",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "IV",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "JE",
    #         "itl1_region_code": "TLZ",
    #         "data_blob": {"itl1_region_name": "Non-ITL1 Region"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "KA",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "KT",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "KW",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "KY",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "L",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LA",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LD",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LE",
    #         "itl1_region_code": "TLF",
    #         "data_blob": {"itl1_region_name": "East Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LL",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LN",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LS",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "LU",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "M",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "ME",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "MK",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "ML",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "N",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NE",
    #         "itl1_region_code": "TLC",
    #         "data_blob": {"itl1_region_name": "North East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NG",
    #         "itl1_region_code": "TLF",
    #         "data_blob": {"itl1_region_name": "East Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NN",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NP",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NR",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "NW",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "OL",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "OX",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PA",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PE",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PH",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PL",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PO",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "PR",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "RG",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "RH",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "RM",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "S",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SA",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SE",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SG",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SK",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SL",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SM",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SN",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SO",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SP",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SR",
    #         "itl1_region_code": "TLC",
    #         "data_blob": {"itl1_region_name": "North East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SS",
    #         "itl1_region_code": "TLH",
    #         "data_blob": {"itl1_region_name": "East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "ST",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SW",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "SY",
    #         "itl1_region_code": "TLL",
    #         "data_blob": {"itl1_region_name": "Wales"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TA",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TD",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TF",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TN",
    #         "itl1_region_code": "TLJ",
    #         "data_blob": {"itl1_region_name": "South East"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TQ",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TR",
    #         "itl1_region_code": "TLK",
    #         "data_blob": {"itl1_region_name": "South West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TS",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "TW",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "UB",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "W",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WA",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WC",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WD",
    #         "itl1_region_code": "TLI",
    #         "data_blob": {"itl1_region_name": "London"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WF",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WN",
    #         "itl1_region_code": "TLD",
    #         "data_blob": {"itl1_region_name": "North West"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WR",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WS",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "WV",
    #         "itl1_region_code": "TLG",
    #         "data_blob": {"itl1_region_name": "West Midlands"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "YO",
    #         "itl1_region_code": "TLE",
    #         "data_blob": {"itl1_region_name": "Yorkshire"},
    #     },
    #     {
    #         "id": uuid.uuid4(),
    #         "postcode_prefix": "ZE",
    #         "itl1_region_code": "TLM",
    #         "data_blob": {"itl1_region_name": "Scotland"},
    #     },
    # ]

    # op.bulk_insert(geospatial_dim, geospatial_data)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geospatial_dim")
    # ### end Alembic commands ###
