"""empty message

Revision ID: 024_jsonb_nullabilities
Revises: 023_add_pg_management_table
Create Date: 2024-03-22 20:38:44.733577

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "024_jsonb_nullabilities"
down_revision = "023_add_pg_management_table"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("funding_comment", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("funding_question", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("outcome_data", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("output_data", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("place_detail", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("private_investment", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("programme_progress", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("project_finance_change", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    with op.batch_alter_table("risk_register", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk_register", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("project_finance_change", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("programme_progress", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("private_investment", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("place_detail", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("output_data", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("outcome_data", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("funding_question", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("funding_comment", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.alter_column("data_blob", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)

    # ### end Alembic commands ###
