"""Added submitting_account_id & submitting_user_email fields to Submission model.

Revision ID: 029_add_account_id_and_email
Revises: 028_normalise_fund_ref_data
Create Date: 2024-05-01 17:00:34.874064

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "029_add_account_id_and_email"
down_revision = "028_normalise_fund_ref_data"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("submitting_account_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("submitting_user_email", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.drop_column("submitting_user_email")
        batch_op.drop_column("submitting_account_id")

    # ### end Alembic commands ###
