"""empty message

Revision ID: 029_project_geospatial_m2m
Revises: 028_normalise_fund_ref_data
Create Date: 2024-03-25 09:11:41.204961

"""

import sqlalchemy as sa
from alembic import op

import core

# revision identifiers, used by Alembic.
revision = "029_project_geospatial_m2m"
down_revision = "028_normalise_fund_ref_data"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "project_geospatial_association",
        sa.Column("project_id", core.db.types.GUID(), nullable=False),
        sa.Column("geospatial_id", core.db.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geospatial_id"],
            ["geospatial_dim.id"],
            name=op.f("fk_project_geospatial_association_geospatial_id_geospatial_dim"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_dim.id"],
            name=op.f("fk_project_geospatial_association_project_id_project_dim"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "geospatial_id", name=op.f("pk_project_geospatial_association")),
    )

    op.execute(
        """
        INSERT INTO project_geospatial_association (project_id, geospatial_id)
        SELECT DISTINCT unnested_project_dim.id, geospatial_dim.id
        FROM (
            SELECT id AS id, unnest(postcodes) AS postcode
            FROM project_dim
        ) as unnested_project_dim
        JOIN geospatial_dim ON geospatial_dim.postcode_prefix = substring(unnested_project_dim.postcode FROM '^[A-Z]+');
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_geospatial_association")
    # ### end Alembic commands ###
