"""Create project_geospatial_association table

Revision ID: 032_project_geospatial_m2m
Revises: 031_programme_junction_2
Create Date: 2024-03-25 09:11:41.204961

"""

import sqlalchemy as sa
from alembic import op

import core

# revision identifiers, used by Alembic.
revision = "032_project_geospatial_m2m"
down_revision = "031_programme_junction_2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "project_geospatial_association",
        sa.Column("project_id", core.db.types.GUID(), nullable=False),
        sa.Column("geospatial_id", core.db.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geospatial_id"],
            ["geospatial_dim.id"],
            name=op.f("fk_project_geospatial_association_geospatial_id_geospatial_dim"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_dim.id"],
            name=op.f("fk_project_geospatial_association_project_id_project_dim"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "geospatial_id", name=op.f("pk_project_geospatial_association")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_geospatial_association")
    # ### end Alembic commands ###
