"""drop geospatial data_blob

Revision ID: 035_drop_geospatial_data_blob
Revises: 034_geospatial_itl1_region_name
Create Date: 2024-05-14 16:00:44.560549

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "035_drop_geospatial_data_blob"
down_revision = "034_geospatial_itl1_region_name"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("geospatial_dim", schema=None) as batch_op:
        batch_op.drop_column("data_blob")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("geospatial_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    op.execute(
        """
            UPDATE geospatial_dim
            SET data_blob = jsonb_build_object(
                'itl1_region_name', itl1_region_name
            )
        """
    )

    # ### end Alembic commands ###
