"""Add PendingSubmission and PendingSubmissionForm tables

Revision ID: 038_add_pending_sub_tables
Revises: 037_drop_submission_reporting_ro
Create Date: 2024-06-05 14:02:00.000000

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import core

# revision identifiers, used by Alembic.
revision = "038_add_pending_sub_tables"
down_revision = "037_drop_submission_reporting_ro"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_submission",
        sa.Column("id", core.db.types.GUID(), nullable=False, primary_key=True),
        sa.Column("fund_name", sa.String(), nullable=False),
        sa.Column("organisation_name", sa.String(), nullable=False),
    )

    op.create_table(
        "pending_submission_form",
        sa.Column("id", core.db.types.GUID(), nullable=False, primary_key=True),
        sa.Column("pending_submission_id", core.db.types.GUID(), nullable=False),
        sa.Column("form_name", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["pending_submission_id"],
            ["pending_submission.id"],
            name=op.f("fk_pending_submission_form_pending_submission_id_pending_submission"),
            ondelete="CASCADE",
        ),
    )

    op.create_index(
        op.f("ix_pending_submission_form_pending_submission_id"), "pending_submission_form", ["pending_submission_id"]
    )
    op.create_index(op.f("ix_pending_submission_form_form_name"), "pending_submission_form", ["form_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_submission_form_form_name"), table_name="pending_submission_form")
    op.drop_index(op.f("ix_pending_submission_form_pending_submission_id"), table_name="pending_submission_form")
    op.drop_table("pending_submission_form")
    op.drop_table("pending_submission")
    # ### end Alembic commands ###
