"""users and projects

Revision ID: 038_users_and_projects
Revises: 037_add_pending_submission_table
Create Date: 2024-06-06 19:55:09.899505

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import core

# revision identifiers, used by Alembic.
revision = "038_users_and_projects"
down_revision = "037_add_pending_submission_table"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email_address", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("id", core.db.types.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email_address", name=op.f("uq_user_email_address")),
    )
    op.create_table(
        "project_ref",
        sa.Column("project_code", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("postcodes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("state", sa.Enum("ACTIVE", "CANCELLED", "COMPLETED", name="projectstatusenum"), nullable=False),
        sa.Column("data_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("programme_id", core.db.types.GUID(), nullable=False),
        sa.Column("id", core.db.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["programme_id"], ["programme_dim.id"], name=op.f("fk_project_ref_programme_id_programme_dim")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_ref")),
        sa.UniqueConstraint("project_code", name=op.f("uq_project_ref_project_code")),
    )
    op.create_table(
        "association_table",
        sa.Column("project_ref_id", core.db.types.GUID(), nullable=True),
        sa.Column("programme_dim_id", core.db.types.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["programme_dim_id"], ["programme_dim.id"], name=op.f("fk_association_table_programme_dim_id_programme_dim")
        ),
        sa.ForeignKeyConstraint(
            ["project_ref_id"], ["project_ref.id"], name=op.f("fk_association_table_project_ref_id_project_ref")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association_table")
    op.drop_table("project_ref")
    op.drop_table("user")
    # ### end Alembic commands ###
