"""Make ingest_date nullable

Revision ID: 045_make_ingest_date_nullable
Revises: 044_remove_old_rr_cols
Create Date: 2024-10-14 10:14:50.453885

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "045_make_ingest_date_nullable"
down_revision = "044_remove_old_rr_cols"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.alter_column("submission_date", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("ingest_date", existing_type=postgresql.TIMESTAMP(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.alter_column("ingest_date", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("submission_date", existing_type=postgresql.TIMESTAMP(), nullable=True)

    # ### end Alembic commands ###
