"""Drop ingest_date

Revision ID: 046_drop_ingest_date
Revises: 045_make_ingest_date_nullable
Create Date: 2024-10-15 13:56:14.650292

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "046_drop_ingest_date"
down_revision = "045_make_ingest_date_nullable"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.drop_column("ingest_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ingest_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
