"""drop_geography

Revision ID: 047_drop_geography
Revises: 046_drop_ingest_date
Create Date: 2024-10-23 11:54:51.580417

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "047_drop_geography"
down_revision = "046_drop_ingest_date"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.drop_column("geography")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("geography", sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
