"""add_external_reference_code

Revision ID: 049_add_external_reference_code
Revises: 048_validate_check_constraints
Create Date: 2024-11-06 11:33:16.537787

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "049_add_external_reference_code"
down_revision = "048_validate_check_constraints"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_reference_code", sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_organisation_dim_external_reference_code"), ["external_reference_code"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_organisation_dim_external_reference_code"), type_="unique")
        batch_op.drop_column("external_reference_code")

    # ### end Alembic commands ###
