"""Add organisation_type

Revision ID: 050_add_organisation_type
Revises: 049_add_external_reference_code
Create Date: 2024-11-11 09:35:33.797563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "050_add_organisation_type"
down_revision = "049_add_external_reference_code"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    org_type_enum = sa.Enum("LOCAL_AUTHORITY", name="organisationtypeenum")
    org_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.add_column(sa.Column("organisation_type", org_type_enum, nullable=True))

    # Update the organisation_type column for existing records
    op.execute("UPDATE organisation_dim SET organisation_type = 'LOCAL_AUTHORITY'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.drop_column("organisation_type")

    # ### end Alembic commands ###
