"""Alter_organisation_type

Revision ID: 051_alter_organisation_type
Revises: 050_add_organisation_type
Create Date: 2024-11-12 12:07:08.823748

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "051_alter_organisation_type"
down_revision = "050_add_organisation_type"
branch_labels = None
depends_on = None

org_type_enum = sa.Enum("LOCAL_AUTHORITY", name="organisationtypeenum")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.alter_column(
            "organisation_type", existing_type=org_type_enum, server_default="LOCAL_AUTHORITY", nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation_dim", schema=None) as batch_op:
        batch_op.alter_column(
            "organisation_type",
            existing_type=org_type_enum,
            server_default=None,
            nullable=True,
        )

    # ### end Alembic commands ###
