"""empty message

Revision ID: 1f312e207cc3
Revises: d9eca05d26a1
Create Date: 2023-06-13 17:32:10.566597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f312e207cc3"
down_revision = "d9eca05d26a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.drop_index("ix_unique_funding")
        batch_op.create_index(
            "ix_unique_funding",
            [
                "submission_id",
                "project_id",
                "funding_source_name",
                "funding_source_type",
                "secured",
                "start_date",
                "end_date",
            ],
            unique=True,
        )

    with op.batch_alter_table("outcome_data", schema=None) as batch_op:
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=8), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outcome_data", schema=None) as batch_op:
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=8), nullable=False)

    with op.batch_alter_table("funding", schema=None) as batch_op:
        batch_op.drop_index("ix_unique_funding")
        batch_op.create_index(
            "ix_unique_funding",
            ["submission_id", "project_id", "funding_source_name", "funding_source_type", "start_date", "end_date"],
            unique=False,
        )

    # ### end Alembic commands ###
