"""empty message

Revision ID: dee94a0080e2
Revises: 1f312e207cc3
Create Date: 2023-06-15 10:43:32.428127

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dee94a0080e2"
down_revision = "1f312e207cc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("funding_comment", schema=None) as batch_op:
        batch_op.alter_column("comment", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("programme_dim", schema=None) as batch_op:
        batch_op.drop_constraint("uq_programme_dim_programme_name", type_="unique")
        batch_op.create_index("ix_unique_programme_name_per_fund", ["programme_name", "fund_type_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("programme_dim", schema=None) as batch_op:
        batch_op.drop_index("ix_unique_programme_name_per_fund")
        batch_op.create_unique_constraint("uq_programme_dim_programme_name", ["programme_name"])

    with op.batch_alter_table("funding_comment", schema=None) as batch_op:
        batch_op.alter_column("comment", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
