from enum import StrEnum


class MIMETYPE(StrEnum):
    XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    JSON = "application/json"


EMAIL_DOMAIN_TO_PLACE_NAMES = {
    "ambervalley.gov.uk": ("Heanor",),
    "ashfield-dc.gov.uk": (
        "Sutton in Ashfield",
        "Kirkby and Sutton (Ashfield)",
    ),
    "barnsley.gov.uk": (
        "Barnsley Town Centre",
        "Goldthorpe",
    ),
    "bedford.gov.uk": ("Bedford",),
    "blackburn.gov.uk": ("Darwen",),
    "blackpool.gov.uk": ("Blackpool",),
    "bolton.gov.uk": (
        "Farnworth",
        "Bolton",
    ),
    "boston.gov.uk": ("Boston",),
    "bradford.gov.uk": (
        "Shipley",
        "Keighley",
    ),
    "broxtowe.gov.uk": ("Stapleford",),
    "buckinghamshire.gov.uk": ("High Wycombe",),
    "calderdale.gov.uk": (
        "Halifax",
        "Brighouse",
        "Todmorden",
        "Elland Town Centre",
    ),
    "charnwood.gov.uk": ("Loughborough",),
    "cheshireeast.gov.uk": ("Crewe",),
    "cheshirewestandchester.gov.uk": ("Winsford",),
    "chesterfield.gov.uk": ("Staveley",),
    "colchester.gov.uk": ("Colchester",),
    "cornwall.gov.uk": (
        "Truro",
        "Camborne",
        "Penzance",
        "St Ives",
    ),
    "durham.gov.uk": ("Bishop Auckland",),
    "herefordshire.gov.uk": ("Hereford",),
    "crawley.gov.uk": ("Crawley",),
    "cumbria.gov.uk": (
        "Workington",
        "Cleator Moor",
        "Millom",
        "Carlisle",
        "Carlisle City Centre",
        "Maryport Town Centre",
    ),
    "darlington.gov.uk": ("Darlington",),
    "derby.gov.uk": ("Derby City Centre, St Peters Cross",),
    "doncaster.gov.uk": (
        "Stainforth",
        "Doncaster",
    ),
    "dover.gov.uk": ("Dover Town Centre and Waterfront",),
    "dudley.gov.uk": (
        "Brierley Hill High Town Centre",
        "Dudley",
    ),
    "e-lindsey.gov.uk": (
        "Skegness",
        "Mablethorpe",
    ),
    "eastriding.gov.uk": ("Goole",),
    "eaststaffsbc.gov.uk": ("Burton",),
    "erewash.gov.uk": ("Long Eaton",),
    "fenland.gov.uk": ("March High Street",),
    "fylde.gov.uk": ("Kirkham Town Centre",),
    "great-yarmouth.gov.uk": ("Great Yarmouth",),
    "royalgreenwich.gov.uk": ("Woolwich Town Centre",),
    "halton.gov.uk": ("Runcorn",),
    "haringey.gov.uk": ("Tottenham High Road",),
    "harlow.gov.uk": ("Harlow",),
    "harrow.gov.uk": ("Wealdstone",),
    "hartlepool.gov.uk": ("Hartlepool",),
    "hastings.gov.uk": ("Hastings",),
    "highpeak.gov.uk": ("Buxton",),
    "huntingdonshire.gov.uk": ("St Neots",),
    "ipswich.gov.uk": ("Ipswich",),
    "west-norfolk.gov.uk": ("King's Lynn",),
    "kirklees.gov.uk": (
        "Morley",
        "Dewsbury",
    ),
    "lewes-eastbourne.gov.uk": ("Newhaven",),
    "lincoln.gov.uk": ("Lincoln",),
    "mansfield.gov.uk": ("Mansfield",),
    "medway.gov.uk": ("Chatham Town Centre",),
    "middlesbrough.gov.uk": (
        "Middlesbrough Centre",
        "Middlesbrough",
    ),
    "milton-keynes.gov.uk": ("Milton Keynes",),
    "newark-sherwooddc.gov.uk": (
        "Newark",
        "Newark-on-Trent",
    ),
    "newcastle-staffs.gov.uk": (
        "Newcastle-Under-Lyme Town Centre",
        "Kidsgrove",
        "Newcastle-under-Lyme",
        "Newcastle-under-Lyme Town Centre",
    ),
    "northdevon.gov.uk": ("Barnstaple",),
    "ne-derbyshire.gov.uk": ("Clay Cross",),
    "nelincs.gov.uk": (
        "Grimsby Town Centre",
        "Grimsby",
    ),
    "northlincs.gov.uk": ("Scunthorpe",),
    "northumberland.gov.uk": (
        "Blyth Town Centre",
        "Blyth",
    ),
    "northyorks.gov.uk": (
        "Northallerton",
        "Scarborough",
        "Whitby",
    ),
    "norwich.gov.uk": ("Norwich",),
    "nottinghamcity.gov.uk": ("Nottingham City Centre, West End Point",),
    "oldham.gov.uk": ("Oldham",),
    "pendle.gov.uk": ("Nelson",),
    "peterborough.gov.uk": ("Peterborough",),
    "plymouth.gov.uk": ("Plymouth City Centre",),
    "portsmouth.gov.uk": (
        "Fratton",
        "Commercial Road",
    ),
    "preston.gov.uk": ("Preston",),
    "redcar-cleveland.gov.uk": (
        "Redcar",
        "Loftus",
    ),
    "redditchbc.gov.uk": ("Redditch",),
    "rochdale.gov.uk": (
        "Rochdale Town Centre",
        "Rochdale",
    ),
    "rotherham.gov.uk": ("Rotherham",),
    "sandwell.gov.uk": (
        "West Bromwich",
        "Rowley Regis",
        "Smethwick",
    ),
    "sefton.gov.uk": ("Southport",),
    "sheffield.gov.uk": (
        "Sheffield High Street",
        "Stocksbridge",
    ),
    "somerset.gov.uk": (
        "Yeovil",
        "Bridgwater",
        "Glastonbury",
        "Taunton",
    ),
    "southglos.gov.uk": ("Kingswood",),
    "southkesteven.gov.uk": ("Grantham",),
    "southribble.gov.uk": ("Leyland",),
    "southtyneside.gov.uk": ("South Shields",),
    "southwark.gov.uk": ("Old Kent Road",),
    "staffordbc.gov.uk": ("Stafford",),
    "stevenage.gov.uk": ("Stevenage",),
    "sthelens.gov.uk": ("St Helens",),
    "stockport.gov.uk": (
        "Stockport",
        "Cheadle",
    ),
    "stockton.gov.uk": (
        "Stockton",
        "Thornaby",
    ),
    "sunderland.gov.uk": ("Sunderland City Centre",),
    "sutton.gov.uk": (
        "Sutton High Street",
        "Sutton",
    ),
    "swindon.gov.uk": ("Swindon",),
    "tamworth.gov.uk": ("Tamworth Town Centre",),
    "teignbridge.gov.uk": ("Newton Abbot",),
    "telford.gov.uk": ("Telford",),
    "thanet.gov.uk": (
        "Ramsgate",
        "Margate",
    ),
    "thurrock.gov.uk": (
        "Tilbury",
        "Grays",
    ),
    "torbay.gov.uk": (
        "Paignton",
        "Torquay",
    ),
    "trafford.gov.uk": ("Stretford",),
    "wakefield.gov.uk": (
        "Wakefield",
        "Castleford",
    ),
    "walsall.gov.uk": (
        "Walsall",
        "Bloxwich",
    ),
    "wandsworth.gov.uk": ("Putney Town Centre",),
    "warrington.gov.uk": ("Warrington",),
    "warwickdc.gov.uk": ("Leamington Town Centre",),
    "wigan.gov.uk": ("Wigan",),
    "wiltshire.gov.uk": (
        "Trowbridge",
        "Salisbury City Centre",
    ),
    "wirral.gov.uk": (
        "New Ferry",
        "Birkenhead",
    ),
    "wolverhampton.gov.uk": (
        "Wolverhampton",
        "Wolverhampton City Centre (West)",
    ),
    "worcester.gov.uk": (
        "Blackfriars - Northern City Centre",
        "Worcester",
    ),
    "wyreforestdc.gov.uk": ("Kidderminster",),
    "bcpcouncil.gov.uk": ("Bournemouth",),
    "eastsuffolk.gov.uk": ("Lowestoft",),
    "northnorthants.gov.uk": ("Corby",),
    "westnorthants.gov.uk": ("Northampton",),
}
