from enum import StrEnum


class MIMETYPE(StrEnum):
    XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    JSON = "application/json"


FUND_TYPE_ID_TO_FRIENDLY_NAME = {
    "TD": "Town Deal",
    "HS": "Future High Streets Fund",
}

EMAIL_DOMAIN_TO_LA_AND_PLACE_NAMES = {
    "ambervalley.gov.uk": (("Amber Valley Borough Council",), ("Heanor",)),
    "ashfield.gov.uk": (("Ashfield District Council",), ("Sutton in Ashfield", "Kirkby and Sutton (Ashfield)")),
    "barnsley.gov.uk": (("Barnsley Metropolitan Borough Council",), ("Barnsley Town Centre", "Goldthorpe")),
    "bedford.gov.uk": (("Bedford Borough Council",), ("Bedford",)),
    "blackburn.gov.uk": (("Blackburn with Darwen Borough Council",), ("Darwen",)),
    "blackpool.gov.uk": (("Blackpool Borough Council",), ("Blackpool",)),
    "bolton.gov.uk": (("Bolton Metropolitan Borough Council",), ("Farnworth", "Bolton")),
    "boston.gov.uk": (("Boston Borough Council",), ("Boston",)),
    "bradford.gov.uk": (("Bradford Council",), ("Shipley", "Keighley")),
    "broxtowe.gov.uk": (("Broxtowe Borough Council",), ("Stapleford",)),
    "buckinghamshire.gov.uk": (("Buckinghamshire Council",), ("High Wycombe",)),
    "calderdale.gov.uk": (
        ("Calderdale Council",),
        ("Halifax", "Brighouse", "Todmorden", "Elland Town Centre"),
    ),
    "charnwood.gov.uk": (("Charnwood Borough Council",), ("Loughborough",)),
    "cheshireeast.gov.uk": (("Cheshire East Council",), ("Crewe",)),
    "cheshirewestandchester.gov.uk": (("Cheshire West and Chester Council",), ("Winsford",)),
    "chesterfield.gov.uk": (("Chesterfield Borough Council",), ("Staveley",)),
    "colchester.gov.uk": (("Colchester City Council",), ("Colchester",)),
    "cornwall.gov.uk": (("Cornwall Council",), ("Truro", "Camborne", "Penzance", "St Ives")),
    "durham.gov.uk": (("Durham County Council",), ("Bishop Auckland",)),
    "herefordshire.gov.uk": (("Herefordshire Council",), ("Hereford",)),
    "crawley.gov.uk": (("Crawley Borough Council",), ("Crawley",)),
    "cumberland.gov.uk": (
        ("Cumberland Council",),
        ("Workington", "Cleator Moor", "Millom", "Carlisle", "Carlisle City Centre", "Maryport Town Centre"),
    ),
    "carlisle.gov.uk": (
        ("Cumberland Council",),
        ("Carlisle City Centre",),
    ),
    "darlington.gov.uk": (("Darlington Borough Council",), ("Darlington",)),
    "derby.gov.uk": (("Derby City",), ("Derby City Centre, St Peters Cross",)),
    "doncaster.gov.uk": (
        ("Doncaster Metropolitan Borough Council",),
        (
            "Stainforth",
            "Doncaster",
        ),
    ),
    "dover.gov.uk": (("Dover District Council",), ("Dover Town Centre and Waterfront",)),
    "dudley.gov.uk": (
        ("Dudley Metropolitan Borough Council",),
        (
            "Brierley Hill High Town Centre",
            "Dudley",
        ),
    ),
    "e-lindsey.gov.uk": (
        ("East Lindsey District Council",),
        (
            "Skegness",
            "Mablethorpe",
        ),
    ),
    "eastriding.gov.uk": (("East Riding of Yorkshire Council",), ("Goole",)),
    "eaststaffsbc.gov.uk": (("East Staffordshire Borough Council",), ("Burton",)),
    "erewash.gov.uk": (("Erewash Borough Council",), ("Long Eaton",)),
    "fenland.gov.uk": (("Fenland District Council",), ("March High Street",)),
    "fylde.gov.uk": (("Fylde Council",), ("Kirkham Town Centre",)),
    "great-yarmouth.gov.uk": (("Great Yarmouth Borough Council",), ("Great Yarmouth",)),
    "royalgreenwich.gov.uk": (("Royal Borough of Greenwich",), ("Woolwich Town Centre",)),
    "halton.gov.uk": (("Halton Borough Council",), ("Runcorn",)),
    "haringey.gov.uk": (("London Borough of Haringey",), ("Tottenham High Road",)),
    "harlow.gov.uk": (("Harlow District Council",), ("Harlow",)),
    "harrow.gov.uk": (("London Borough of Harrow",), ("Wealdstone",)),
    "hartlepool.gov.uk": (("Hartlepool Borough Council",), ("Hartlepool",)),
    "hastings.gov.uk": (("Hastings Borough Council",), ("Hastings",)),
    "highpeak.gov.uk": (("High Peak Borough Council",), ("Buxton",)),
    "huntingdonshire.gov.uk": (("Huntingdonshire District Council",), ("St Neots",)),
    "ipswich.gov.uk": (("Ipswich Borough Council",), ("Ipswich",)),
    "west-norfolk.gov.uk": (("King's Lynn and West Norfolk",), ("King's Lynn",)),
    "kirklees.gov.uk": (("Kirklees Council",), ("Dewsbury")),
    "leeds.gov.uk": (("Leeds Council",), ("Morley")),
    "lewes-eastbourne.gov.uk": (("Lewes District Council",), ("Eastbourne Borough Council", "Newhaven")),
    "lincoln.gov.uk": (("City of Lincoln Council",), ("Lincoln",)),
    "mansfield.gov.uk": (("Mansfield District Council",), ("Mansfield",)),
    "medway.gov.uk": (("Medway Council",), ("Chatham Town Centre",)),
    "middlesbrough.gov.uk": (
        ("Middlesbrough Council",),
        (
            "Middlesbrough Centre",
            "Middlesbrough",
        ),
    ),
    "milton-keynes.gov.uk": (("Milton Keynes City Council",), ("Milton Keynes",)),
    "newark-sherwooddc.gov.uk": (
        ("Newark and Sherwood District Council",),
        (
            "Newark",
            "Newark-on-Trent",
        ),
    ),
    "newcastle-staffs.gov.uk": (
        ("Newcastle-under-Lyme Borough Council",),
        (
            "Newcastle-Under-Lyme Town Centre",
            "Kidsgrove",
            "Newcastle-under-Lyme",
            "Newcastle-under-Lyme Town Centre",
        ),
    ),
    "northdevon.gov.uk": (("North Devon Council",), ("Barnstaple",)),
    "ne-derbyshire.gov.uk": (("North East Derbyshire District Council",), ("Clay Cross",)),
    "nelincs.gov.uk": (
        ("North East Lincolnshire Council",),
        (
            "Grimsby Town Centre",
            "Grimsby",
        ),
    ),
    "northlincs.gov.uk": (("North Lincolnshire Council",), ("Scunthorpe",)),
    "northumberland.gov.uk": (
        ("Northumberland County Council",),
        (
            "Blyth Town Centre",
            "Blyth",
        ),
    ),
    "northyorks.gov.uk": (
        ("North Yorkshire Council",),
        (
            "Northallerton",
            "Scarborough",
            "Whitby",
        ),
    ),
    "hambleton.gov.uk": (
        ("North Yorkshire Council",),
        (
            "Northallerton",
            "Scarborough",
            "Whitby",
        ),
    ),
    "norwich.gov.uk": (("Norwich City Council",), ("Norwich",)),
    "nottinghamcity.gov.uk": (("Nottingham City Council",), ("Nottingham City Centre, West End Point",)),
    "nuneatonandbedworth.gov.uk": (
        ("Nuneaton & Bedworth Borough Council",),
        (
            "Nuneaton Town Centre",
            "Nuneaton",
        ),
    ),
    "oldham.gov.uk": (("Oldham Metropolitan Borough Council",), ("Oldham",)),
    "pendle.gov.uk": (("Pendle Borough Council",), ("Nelson",)),
    "peterborough.gov.uk": (("Peterborough City Council",), ("Peterborough",)),
    "plymouth.gov.uk": (("Plymouth City Council",), ("Plymouth City Centre",)),
    "portsmouth.gov.uk": (
        ("Portsmouth City Council",),
        (
            "Fratton",
            "Commercial Road",
        ),
    ),
    "portsmouthcc.gov.uk": (("Portsmouth City Council",), ("Fratton",)),
    "preston.gov.uk": (("Preston City Council",), ("Preston",)),
    "redcar-cleveland.gov.uk": (
        ("Redcar & Cleveland Borough Council",),
        (
            "Redcar",
            "Loftus",
        ),
    ),
    "redditchbc.gov.uk": (("Redditch Borough Council",), ("Redditch",)),
    "rochdale.gov.uk": (("Rochdale Borough Council",), ("Rochdale Town Centre", "Rochdale")),
    "rotherham.gov.uk": (("Rotherham Metropolitan Borough Council",), ("Rotherham",)),
    "sandwell.gov.uk": (("Sandwell Council",), ("West Bromwich", "Rowley Regis", "Smethwick")),
    "sefton.gov.uk": (("Sefton Metropolitan Borough Council",), ("Southport",)),
    "sheffield.gov.uk": (("Sheffield City Council",), ("Sheffield High Street", "Stocksbridge")),
    "somerset.gov.uk": (
        ("Somerset Council",),
        ("Yeovil", "Bridgwater", "Glastonbury", "Taunton"),
    ),
    "southglos.gov.uk": (("South Gloucestershire Council",), ("Kingswood",)),
    "southkesteven.gov.uk": (("South Kesteven District Council",), ("Grantham",)),
    "southribble.gov.uk": (("South Ribble Borough Council",), ("Leyland",)),
    "chorley.gov.uk": (("South Ribble Borough Council",), ("Leyland",)),
    "southtyneside.gov.uk": (("South Tyneside Council",), ("South Shields",)),
    "southwark.gov.uk": (("London Borough of Southwark",), ("Old Kent Road",)),
    "staffordbc.gov.uk": (("Stafford Borough Council",), ("Stafford",)),
    "stevenage.gov.uk": (("Stevenage Borough Council",), ("Stevenage",)),
    "sthelens.gov.uk": (("St Helens Council",), ("St Helens",)),
    "stockport.gov.uk": (("Stockport Metropolitan Borough Council",), ("Stockport", "Cheadle")),
    "stockton.gov.uk": (("Stockton-on-Tees Borough Council",), ("Stockton", "Thornaby")),
    "sunderland.gov.uk": (("Sunderland City Council",), ("Sunderland City Centre",)),
    "sutton.gov.uk": (("London Borough of Sutton",), ("London Borough of Sutton Council", "Sutton")),
    "swindon.gov.uk": (("Swindon Borough Council",), ("Swindon",)),
    "tamworth.gov.uk": (("Tamworth Borough Council",), ("Tamworth Town Centre",)),
    "teignbridge.gov.uk": (("Teignbridge District Council",), ("Newton Abbot",)),
    "telford.gov.uk": (("Telford & Wrekin Council",), ("Telford",)),
    "thanet.gov.uk": (("Thanet District Council",), ("Ramsgate", "Margate")),
    "thurrock.gov.uk": (("Thurrock Borough Council",), ("Tilbury", "Grays")),
    "torbay.gov.uk": (("Torbay Council",), ("Paignton", "Torquay")),
    "trafford.gov.uk": (("Trafford Council",), ("Stretford",)),
    "wakefield.gov.uk": (("Wakefield Metropolitan District Council",), ("Wakefield", "Castleford")),
    "walsall.gov.uk": (("Walsall Council",), ("Walsall", "Bloxwich")),
    "richmondandwandsworth.gov.uk": (("London Borough of Wandsworth",), ("Putney Town Centre",)),
    "warrington.gov.uk": (("Warrington Borough Council",), ("Warrington",)),
    "warwickdc.gov.uk": (("Warwick District Council",), ("Leamington Town Centre",)),
    "westmorlandandfurness.gov.uk": (("Westmorland & Furness Council",), ("Barrow",)),
    "wigan.gov.uk": (("Wigan Council",), ("Wigan",)),
    "wiltshire.gov.uk": (("Wiltshire Council",), ("Trowbridge", "Salisbury City Centre")),
    "wirral.gov.uk": (("Wirral Council",), ("New Ferry", "Birkenhead")),
    "wolverhampton.gov.uk": (("City of Wolverhampton Council",), ("Wolverhampton", "Wolverhampton City Centre (West)")),
    "worcester.gov.uk": (("Worcester City Council",), ("Blackfriars - Northern City Centre", "Worcester")),
    "wyreforestdc.gov.uk": (("Wyre Forest District Council",), ("Kidderminster",)),
    "bcpcouncil.gov.uk": (("Bournemouth, Christchurch and Poole Council",), ("Bournemouth",)),
    "eastsuffolk.gov.uk": (("East Suffolk Council",), ("Lowestoft",)),
    "northnorthants.gov.uk": (("North Northamptonshire Council",), ("Corby",)),
    "corby.gov.uk": (("North Northamptonshire Council",), ("Corby",)),
    "westnorthants.gov.uk": (("West Northamptonshire Council",), ("Northampton",)),
}
