[package]
name = "funding-service-design-frontend"
version = "0.1.1"
description = "The funding service design frontend for the DLUHC."
authors = ["Evoco Digital Services"]
license = "MIT License"

[tool.black]
line-length = 120
experimental-string-processing = 1

[tool.djlint]
# run with : `djlint path/to/file.html --reformat --format-css --format-js`
#   this is deliberately commented out.  we don't want to format these tags as
#   it will introduce new lines and tabs, making the translation matching brittle.
# custom_blocks="trans,endtrans"
max_line_length=1000        # high limit, we don't want line breaks for translations.
max_attribute_length=1000   # ^^^
exclude=".venv,venv"
profile="jinja2"


[tool.flake8]
max-line-length = 120
count = true
