# flake8: noqa
MOCK_PACKAGE_RESPONSE = {
    "cfo_email": "jane.doe2@example.gov.uk",
    "contact_email": "jane.doe2@example.gov.uk",
    "fund_type_id": "FHSF",
    "m_and_e_email": "jane.doe2@example.gov.uk",
    "organisation": "Fake Council Name",
    "package_id": "FHSF001",
    "package_name": "Leaky Cauldron regeneration",
    "project_sro_email": "jane.doe2@example.gov.uk",
}

MOCK_PROJECT_RESPONSE = {
    "address": "SW1A 2AA",
    "capital": [
        {
            "amount": 123.0,
            "end_date": "2020-09-30T00:00:00Z",
            "project_id": "FHSFDCC001",
            "start_date": "2020-04-01T00:00:00Z",
            "state": "Actual",
        }
    ],
    "direct_fund": [
        {
            "amount": 0.0,
            "contractually_committed_amount": 0.0,
            "end_date": "2021-03-31T00:00:00Z",
            "pra_or_other": "PRA",
            "project_id": "FHSFDCC001",
            "start_date": "2020-10-01T00:00:00Z",
            "state": "Actual",
        },
        {
            "amount": 12345678.0,
            "contractually_committed_amount": 12345678.0,
            "end_date": "2021-09-30T00:00:00Z",
            "pra_or_other": "PRA",
            "project_id": "FHSFDCC001",
            "start_date": "2021-04-01T00:00:00Z",
            "state": "Actual",
        },
    ],
    "indirect_fund_secured": [
        {
            "amount": 1234567.0,
            "end_date": "2022-03-31T00:00:00Z",
            "funding_source_category": "Local Authority",
            "funding_source_name": "Gotham City Council",
            "project_id": "FHSFDCC001",
            "start_date": "2021-10-01T00:00:00Z",
            "state": "Actual",
        },
        {
            "amount": 1234567.0,
            "end_date": "2022-09-30T00:00:00Z",
            "funding_source_category": "Local Authority",
            "funding_source_name": "Gotham City Council",
            "project_id": "FHSFDCC001",
            "start_date": "2022-04-01T00:00:00Z",
            "state": "Forecast",
        },
    ],
    "indirect_fund_unsecured": [
        {
            "amount": 0.0,
            "comments": "",
            "current_status": "",
            "end_date": "2021-06-30T00:00:00Z",
            "funding_source_category": "Private Funding",
            "funding_source_name": "Private Funding",
            "potential_secure_date": "NaTZ",
            "project_id": "FHSFDCC001",
            "start_date": "2021-04-01T00:00:00Z",
            "state": "Actual",
        },
        {
            "amount": 1234567.0,
            "comments": "",
            "current_status": "",
            "end_date": "2022-06-30T00:00:00Z",
            "funding_source_category": "Private Funding",
            "funding_source_name": "Private Funding",
            "potential_secure_date": "NaTZ",
            "project_id": "FHSFDCC001",
            "start_date": "2022-04-01T00:00:00Z",
            "state": "Forecast",
        },
    ],
    "outcome_data": [
        {
            "amount": 0,
            "end_date": "2020-04-30T00:00:00Z",
            "geography_indicator": "Town",
            "outcome": "Year on Year % Change in Monthly Footfall",
            "outcome_category": "Place",
            "project_id": "FHSFDCC001",
            "start_date": "2020-04-01T00:00:00Z",
            "state": "Actual",
            "unit_of_measurement": "Year on Year % Change in Monthly Footfall",
        },
        {
            "amount": 0,
            "end_date": "2020-05-31T00:00:00Z",
            "geography_indicator": "Town",
            "outcome": "Year on Year % Change in Monthly Footfall",
            "outcome_category": "Place",
            "project_id": "FHSFDCC001",
            "start_date": "2020-05-01T00:00:00Z",
            "state": "Actual",
            "unit_of_measurement": "Year on Year % Change in Monthly Footfall",
        },
    ],
    "output_data": [
        {
            "amount": 0.0,
            "end_date": "2020-09-30T00:00:00Z",
            "output": "#of temporary FT jobs supported",
            "output_category": "Jobs",
            "project_id": "FHSFDCC001",
            "start_date": "2020-04-01T00:00:00Z",
            "state": "Actual",
            "unit_of_measurement": "Number of jobs",
        },
        {
            "amount": 0.0,
            "end_date": "2020-09-30T00:00:00Z",
            "output": " (FTE) permanent jobs created",
            "output_category": "Jobs",
            "project_id": "FHSFDCC001",
            "start_date": "2020-04-01T00:00:00Z",
            "state": "Actual",
            "unit_of_measurement": "Number of jobs",
        },
        {
            "amount": 0.0,
            "end_date": "2021-03-31T00:00:00Z",
            "output": " (FTE) permanent jobs safe-guarded",
            "output_category": "Jobs",
            "project_id": "FHSFDCC001",
            "start_date": "2020-10-01T00:00:00Z",
            "state": "Actual",
            "unit_of_measurement": "Number of jobs",
        },
        {
            "amount": 0.0,
            "end_date": "2026-03-31T00:00:00Z",
            "output": "# of heritage buildings renovated/restored",
            "output_category": "test field - missing data",
            "project_id": "FHSFDCC001",
            "start_date": "2025-10-01T00:00:00Z",
            "state": "Forecast",
            "unit_of_measurement": "Number of buildings",
        },
    ],
    "package_id": "FHSF001",
    "procurement": [
        {
            "comments": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "completion_date": "2022-03-01T00:00:00Z",
            "construction_contract": "Contract_1",
            "procurement_status": "1. Publication of ITT",
            "project_id": "FHSFDCC001",
            "start_date": "2022-01-01T00:00:00Z",
            "status": "3. Ongoing - delayed",
        }
    ],
    "project_delivery_plan": [
        {
            "comments": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "finish_date": "2024-03-31T00:00:00Z",
            "milestone": "Project start and finish date",
            "project_id": "FHSFDCC001",
            "start_date": "2017-10-01T00:00:00Z",
            "status": "2. Ongoing - on track",
        },
        {
            "comments": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "finish_date": "2024-03-31T00:00:00Z",
            "milestone": "Key Risk Ratings",
            "project_id": "FHSFDCC001",
            "start_date": "2017-10-01T00:00:00Z",
            "status": "2. Ongoing - on track",
        },
    ],
    "project_id": "FHSFDCC001",
    "project_name": "Three Broomsticks regeneration",
    "project_progress": [
        {
            "answer_1": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "answer_2": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "answer_3": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "answer_4": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "answer_5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "answer_6": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "package_id": "FHSF001",
        }
    ],
    "risk_register": [
        {
            "consequences": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit.",
            "full_desc": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. 1",
            "mitigations": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. Mitigation 9",
            "post_mitigated_impact": "3 - Medium impact",
            "post_mitigated_likelihood": "1 - Low",
            "pre_mitigated_impact": "4 - Significant impact",
            "pre_mitigated_likelihood": "3 - High",
            "project_id": "FHSFDCC001",
            "proximity": "3 - Approaching: next 6 months",
            "risk_category": "Rising Costs",
            "risk_name": "Cost and availability of materials",
            "risk_owner_role": "Jane Doe, Head of Property Services",
            "short_desc": "Lorem Ipsum",
        },
        {
            "consequences": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit.",
            "full_desc": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. 2",
            "mitigations": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. Mitigation 10",
            "post_mitigated_impact": "3 - Medium impact",
            "post_mitigated_likelihood": "1 - Low",
            "pre_mitigated_impact": "3 - Medium impact",
            "pre_mitigated_likelihood": "2 - Medium",
            "project_id": "FHSFDCC001",
            "proximity": "1 - Remote",
            "risk_category": "Premises & Estate Management",
            "risk_name": "Occupancy levels",
            "risk_owner_role": "Jane Doe General Manager",
            "short_desc": "Lorem Ipsum",
        },
        {
            "consequences": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit.",
            "full_desc": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. 3",
            "mitigations": "Lorem ipsum dolor sit amet, consectetur "
            "adipiscing elit. Mitigation 11",
            "post_mitigated_impact": "2 - Low impact",
            "post_mitigated_likelihood": "2 - Medium",
            "pre_mitigated_impact": "3 - Medium impact",
            "pre_mitigated_likelihood": "3 - High",
            "project_id": "FHSFDCC001",
            "proximity": "2 - Distant: next 12 months",
            "risk_category": "Reputational Risk",
            "risk_name": "Impact on surrounding area",
            "risk_owner_role": "Jane Doe- Project Manager",
            "short_desc": "Lorem Ipsum",
        },
    ],
    "secondary_organisation": "",
}
