name: Deploy post-award branch to AWS
run-name: Deploy branch ${{ github.ref_name }} to ${{ inputs.environment || 'test' }} (${{ format('SHA:{0}', github.sha) }})
on:
  workflow_dispatch:
    inputs:
        environment:
          description:  Which AWS Account to use
          type: choice
          required: true
          options:
          - dev
        run_e2e_tests:
          description: Run end-to-end tests?
          type: boolean
          default: true
          required: true

jobs:
  paketo_build:
    name: Build post-award image
    permissions:
      packages: write
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/package.yml@uv-requirements
    with:
      assets_required: true
      version_to_build:  ${{ github.sha }}
      owner: ${{ github.repository_owner }}
      application: ${{ github.event.repository.name }}

  deploy:
    name: Deploy to ${{ inputs.environment || 'test' }}
    needs: [ paketo_build ]
    concurrency:
      group: deploy-${{ inputs.environment || 'test' }}
      cancel-in-progress: false
    uses: ./.github/workflows/aws_copilot_deployment.yml
    with:
      copilot_environment: ${{ inputs.environment || 'test' }}
      image_location: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
    secrets: inherit
